import { Router } from "express";
import prisma from "../lib/prisma.js";
import { requireSuperAdmin } from "../middleware/adminAuth.js";
import { writeSuperAdminAudit } from "../lib/adminAuditLog.js";
const router=Router(); router.use(requireSuperAdmin);
async function actor(req){return prisma.user.findUnique({where:{id:req.admin.userId},select:{id:true,name:true,email:true}});}
function formatPlan(plan,allModules=[]){const enabled=new Set(plan.planModules?.map(i=>i.moduleId)||[]);return {id:plan.id,key:plan.key,name:plan.name,description:plan.description||"",tagline:plan.tagline||"",monthlyPrice:Number(plan.monthlyPrice||0),yearlyPrice:plan.yearlyPrice!=null?Number(plan.yearlyPrice):null,active:plan.active,createdAt:plan.createdAt,updatedAt:plan.updatedAt,modules:allModules.map(m=>({id:m.id,key:m.key,name:m.name,description:m.description,icon:m.icon,route:m.route,sortOrder:m.sortOrder,active:m.active,enabled:enabled.has(m.id)}))};}
async function getPlans(){const [ps,ms]=await Promise.all([prisma.plan.findMany({include:{planModules:true},orderBy:{monthlyPrice:"asc"}}),prisma.module.findMany({orderBy:{sortOrder:"asc"}})]);return ps.map(p=>formatPlan(p,ms));}
router.get("/",async(req,res)=>{try{return res.json({success:true,plans:await getPlans()});}catch(e){console.error(e);return res.status(500).json({success:false,message:"Unable to fetch plans"});}});
router.patch("/:planId",async(req,res)=>{try{const existing=await prisma.plan.findUnique({where:{id:req.params.planId}});if(!existing)return res.status(404).json({success:false,message:"Plan not found"});const data={};if(req.body.name!==undefined){const v=String(req.body.name||"").trim();if(!v)return res.status(400).json({success:false,message:"Plan name is required"});data.name=v;}if(req.body.tagline!==undefined)data.tagline=req.body.tagline?String(req.body.tagline).trim():null;if(req.body.description!==undefined)data.description=req.body.description?String(req.body.description).trim():null;if(req.body.monthlyPrice!==undefined){const v=Number(req.body.monthlyPrice);if(!Number.isFinite(v)||v<0)return res.status(400).json({success:false,message:"Invalid monthly price"});data.monthlyPrice=v;}if(req.body.yearlyPrice!==undefined){if(req.body.yearlyPrice===""||req.body.yearlyPrice===null)data.yearlyPrice=null;else{const v=Number(req.body.yearlyPrice);if(!Number.isFinite(v)||v<0)return res.status(400).json({success:false,message:"Invalid yearly price"});data.yearlyPrice=v;}}if(typeof req.body.active==="boolean")data.active=req.body.active;const updated=await prisma.plan.update({where:{id:existing.id},data});const a=await actor(req);await writeSuperAdminAudit({req,actor:a,action:"PLAN_UPDATED",entityType:"PLAN",entityId:updated.id,summary:`${a?.name||"Super Admin"} updated the ${updated.name} plan.`,metadata:{changedFields:Object.keys(data),key:updated.key,active:updated.active}});const p=(await getPlans()).find(x=>x.id===updated.id);return res.json({success:true,message:"Plan updated successfully",plan:p});}catch(e){console.error(e);return res.status(500).json({success:false,message:"Unable to update plan"});}});
router.patch("/:planId/modules/:moduleId",async(req,res)=>{try{const enabled=req.body?.enabled===true;const [plan,m]=await Promise.all([prisma.plan.findUnique({where:{id:req.params.planId}}),prisma.module.findUnique({where:{id:req.params.moduleId}})]);if(!plan)return res.status(404).json({success:false,message:"Plan not found"});if(!m)return res.status(404).json({success:false,message:"Module not found"});if(enabled&&!m.active)return res.status(400).json({success:false,message:"Activate the module globally before adding it to a plan"});if(enabled)await prisma.planModule.upsert({where:{planId_moduleId:{planId:plan.id,moduleId:m.id}},update:{},create:{planId:plan.id,moduleId:m.id}});else await prisma.planModule.deleteMany({where:{planId:plan.id,moduleId:m.id}});const a=await actor(req);await writeSuperAdminAudit({req,actor:a,action:enabled?"PLAN_MODULE_ENABLED":"PLAN_MODULE_DISABLED",entityType:"PLAN_MODULE",entityId:m.id,summary:`${a?.name||"Super Admin"} ${enabled?"added":"removed"} ${m.name} ${enabled?"to":"from"} ${plan.name}.`,metadata:{planKey:plan.key,moduleKey:m.key,enabled}});const p=(await getPlans()).find(x=>x.id===plan.id);return res.json({success:true,message:enabled?`${m.name} added to ${plan.name}`:`${m.name} removed from ${plan.name}`,plan:p});}catch(e){console.error(e);return res.status(500).json({success:false,message:"Unable to update plan module"});}});
export default router;