import { Router } from "express";
import prisma from "../lib/prisma.js";
import { requireSuperAdmin } from "../middleware/adminAuth.js";
import { writeSuperAdminAudit } from "../lib/adminAuditLog.js";
const router=Router();router.use(requireSuperAdmin);
async function actor(req){return prisma.user.findUnique({where:{id:req.admin.userId},select:{id:true,name:true,email:true}});}
function formatModule(m){return{id:m.id,key:m.key,name:m.name,description:m.description||"",icon:m.icon||"",route:m.route||"",sortOrder:m.sortOrder,active:m.active,createdAt:m.createdAt,updatedAt:m.updatedAt,plans:m.planModules?.map(i=>({id:i.plan.id,key:i.plan.key,name:i.plan.name,active:i.plan.active}))||[],clientCount:m.companyModules?.length||0,enabledClientCount:m.companyModules?.filter(i=>i.enabled).length||0};}
async function getModules(){const ms=await prisma.module.findMany({include:{planModules:{include:{plan:true}},companyModules:{select:{id:true,enabled:true}}},orderBy:[{sortOrder:"asc"},{name:"asc"}]});return ms.map(formatModule);}
router.get("/",async(req,res)=>{try{return res.json({success:true,modules:await getModules()});}catch(e){console.error(e);return res.status(500).json({success:false,message:"Unable to fetch modules"});}});
router.patch("/:moduleId",async(req,res)=>{try{const existing=await prisma.module.findUnique({where:{id:req.params.moduleId}});if(!existing)return res.status(404).json({success:false,message:"Module not found"});const data={};if(req.body.name!==undefined){const v=String(req.body.name||"").trim();if(!v)return res.status(400).json({success:false,message:"Module name is required"});data.name=v;}if(req.body.description!==undefined)data.description=req.body.description?String(req.body.description).trim():null;if(req.body.icon!==undefined)data.icon=req.body.icon?String(req.body.icon).trim():null;if(req.body.route!==undefined)data.route=req.body.route?String(req.body.route).trim():null;if(req.body.sortOrder!==undefined){const v=Number(req.body.sortOrder);if(!Number.isInteger(v)||v<0)return res.status(400).json({success:false,message:"Sort order must be a non-negative integer"});data.sortOrder=v;}if(typeof req.body.active==="boolean")data.active=req.body.active;const updated=await prisma.$transaction(async tx=>{const saved=await tx.module.update({where:{id:existing.id},data});if(data.active===false)await tx.companyModule.updateMany({where:{moduleId:existing.id,enabled:true},data:{enabled:false}});return saved;});const a=await actor(req);await writeSuperAdminAudit({req,actor:a,action:"MODULE_UPDATED",entityType:"MODULE",entityId:updated.id,summary:`${a?.name||"Super Admin"} updated the ${updated.name} module.`,metadata:{changedFields:Object.keys(data),key:updated.key,active:updated.active}});const m=(await getModules()).find(x=>x.id===updated.id);return res.json({success:true,message:data.active===false?"Module updated and disabled for all clients":"Module updated successfully",module:m});}catch(e){console.error(e);return res.status(500).json({success:false,message:"Unable to update module"});}});
export default router;