import { Router } from "express";
import prisma from "../lib/prisma.js";
import { requireClientUser } from "../middleware/clientAuth.js";
const router = Router();
router.use(requireClientUser);
const validYear = (v) => { const y=Number(v); return Number.isInteger(y)&&y>=2000&&y<=2100?y:null; };
async function ensureCurrent(companyId){const year=new Date().getFullYear();await prisma.companyWorkspaceYear.upsert({where:{companyId_year:{companyId,year}},update:{},create:{companyId,year,structureMode:"CURRENT"}});}
router.get("/",async(req,res)=>{try{const companyId=req.clientUser.companyId;await ensureCurrent(companyId);const [ws,leads,admissions]=await Promise.all([prisma.companyWorkspaceYear.findMany({where:{companyId}}),prisma.lead.findMany({where:{companyId},select:{createdAt:true}}),prisma.admission.findMany({where:{companyId},select:{admissionDate:true}})]);const known=new Set(ws.map(x=>x.year));const discovered=new Set([...leads.map(x=>new Date(x.createdAt).getFullYear()),...admissions.map(x=>new Date(x.admissionDate).getFullYear())]);for(const year of discovered){if(validYear(year)&&!known.has(year))await prisma.companyWorkspaceYear.upsert({where:{companyId_year:{companyId,year}},update:{},create:{companyId,year,structureMode:"EXISTING"}});}const years=await prisma.companyWorkspaceYear.findMany({where:{companyId},orderBy:{year:"desc"}});return res.json({success:true,years});}catch(e){console.error("Load workspace years failed:",e);return res.status(500).json({success:false,message:"Unable to load workspace years"});}});
router.post("/",async(req,res)=>{try{const companyId=req.clientUser.companyId;const year=validYear(req.body?.year);const mode=String(req.body?.mode||"EMPTY").toUpperCase();if(!year)return res.status(400).json({success:false,message:"Enter a valid year between 2000 and 2100"});if(!["EMPTY","COPY_STRUCTURE"].includes(mode))return res.status(400).json({success:false,message:"Invalid workspace creation mode"});const existing=await prisma.companyWorkspaceYear.findUnique({where:{companyId_year:{companyId,year}}});if(existing)return res.status(409).json({success:false,message:`${year} workspace already exists`});const copiedFromYear=mode==="COPY_STRUCTURE"?validYear(req.body?.copiedFromYear):null;const workspace=await prisma.companyWorkspaceYear.create({data:{companyId,year,structureMode:mode,copiedFromYear}});return res.status(201).json({success:true,message:`${year} workspace created`,workspace});}catch(e){console.error("Create workspace year failed:",e);return res.status(500).json({success:false,message:"Unable to create year workspace"});}});
export default router;